Repository T-kitaka/velog-clone-backend, pull requests merged in 2025-03, with the labels that each got.

#2 feat(#1): 회원가입 추가
  .github/ISSUE_TEMPLATE/❓-question.md
  .github/ISSUE_TEMPLATE/⭐️-feature-.md
  .github/ISSUE_TEMPLATE/🐞-bug.md
  .github/pull_request_template.md
  src/main/java/com/spring/velogcloneproject/common/exception/CodeInterface.java
  src/main/java/com/spring/velogcloneproject/common/exception/CustomException.java
  src/main/java/com/spring/velogcloneproject/common/exception/ErrorCode.java
  src/main/java/com/spring/velogcloneproject/user/controller/UserController.java
  src/main/java/com/spring/velogcloneproject/user/domain/User.java
  src/main/java/com/spring/velogcloneproject/user/domain/UserBuilder.java
  src/main/java/com/spring/velogcloneproject/user/domain/dto/UserDTO.java
  src/main/java/com/spring/velogcloneproject/user/domain/dto/UserRegisterResponseDTO.java
  src/main/java/com/spring/velogcloneproject/user/repository/UserRepositoryV1.java
  src/main/java/com/spring/velogcloneproject/user/repository/UserRepositoryV1Impl.java
  src/main/java/com/spring/velogcloneproject/user/service/UserService.java
Labels: 🔥 backend, ⭐️ feature

#4 feat(#3): CI/CD 파이프라인 구축
  .github/workflows/backend_ci.yml
  .github/workflows/backend_dev_cd.yml
  .github/workflows/backend_main_cd.yml
  Dockerfile
Labels: ⚙️ chore

#6 feat(#5): 게시글 작성 기능 추가
  build.gradle
  src/main/java/com/spring/velogcloneproject/common/exception/CodeInterface.java
  src/main/java/com/spring/velogcloneproject/common/exception/CustomException.java
  src/main/java/com/spring/velogcloneproject/common/exception/ErrorCode.java
  src/main/java/com/spring/velogcloneproject/config/ModelMapperConfig.java
  src/main/java/com/spring/velogcloneproject/post/controller/PostController.java
  src/main/java/com/spring/velogcloneproject/post/domain/Post.java
  src/main/java/com/spring/velogcloneproject/post/domain/dto/PostConverter.java
  src/main/java/com/spring/velogcloneproject/post/domain/dto/PostCreateRequest.java
  src/main/java/com/spring/velogcloneproject/post/domain/dto/PostCreateResponse.java
  src/main/java/com/spring/velogcloneproject/post/repository/PostMemoryRepositoryImpl.java
  src/main/java/com/spring/velogcloneproject/post/repository/PostRepository.java
  src/main/java/com/spring/velogcloneproject/post/service/PostService.java
  src/main/java/com/spring/velogcloneproject/user/controller/UserController.java
  src/main/java/com/spring/velogcloneproject/user/domain/User.java
  src/main/java/com/spring/velogcloneproject/user/domain/UserBuilder.java
  src/main/java/com/spring/velogcloneproject/user/domain/dto/UserDTO.java
  src/main/java/com/spring/velogcloneproject/user/domain/dto/UserRegisterResponseDTO.java
  src/main/java/com/spring/velogcloneproject/user/repository/UserRepositoryV1.java
  src/main/java/com/spring/velogcloneproject/user/repository/UserRepositoryV1Impl.java
  src/main/java/com/spring/velogcloneproject/user/service/UserService.java
  src/test/java/com/spring/velogcloneproject/post/repository/PostRepositoryTest.java
  src/test/java/com/spring/velogcloneproject/post/service/PostServiceTest.java
Labels: 🔥 backend, ⚙️ chore, ⭐️ feature, ♻️ refactor, ✅ test

#8 ci(#7): Develop에 있는 ci/cd merge
  .github/workflows/backend_ci.yml
  .github/workflows/backend_dev_cd.yml
  .github/workflows/backend_main_cd.yml
  Dockerfile
Labels: ⚙️ chore
